export const SET_TIMETABLE = "SET_TIMETABLE";
export const SET_DISCIPLINE = "SET_DISCIPLINE";
export const SET_TEACHER = "SET_TEACHER";
export const SET_GROUP = "SET_GROUP";
export const EDIT_TIMETABLE = "EDIT_TIMETABLE";
